//! The "managed by bukagu" banner prepended to every mapped destination file.
//!
//! v2 doesn't copy a source file byte-for-byte into its target; it writes the
//! source's contents **plus a one-line comment banner** at the top, warning that
//! the file is overwritten on each sync and pointing at the real source to edit.
//! The comment syntax is chosen by the target's extension ([`comment_style`]).
//!
//! Writing is **idempotent**: [`with_banner`] strips any banner bukagu wrote
//! before re-adding a fresh one, so re-syncing never stacks banners. The banner is
//! inserted **after** a leading byte-order mark and/or `#!` shebang line so a BOM
//! stays first and interpreter scripts keep running.

use std::path::Path;

/// Stable phrase that opens every banner; also how [`strip_existing`] recognises a
/// banner bukagu wrote previously (matched case-insensitively). Keep it stable —
/// changing it would orphan banners already written into destinations.
pub const BANNER_MARKER: &str = "Managed by bukagu";

/// How a file's line / block comments are written, picked by extension.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// A line comment with the given prefix, e.g. `//` or `#`.
    Line(&'static str),
    /// A block comment wrapping the text, e.g. `/* … */` or `<!-- … -->`.
    Block {
        open: &'static str,
        close: &'static str,
    },
}

/// The comment syntax for a file extension (lower-cased), or `None` when bukagu
/// doesn't know how to comment it — in which case the mapping engine copies the
/// file verbatim with no banner. The table is representative, not exhaustive.
pub fn comment_style(ext: &str) -> Option<CommentStyle> {
    use CommentStyle::{Block, Line};
    let style = match ext.to_ascii_lowercase().as_str() {
        // Slash line comments (C family, JS/TS, Rust, Go, …).
        "rs" | "js" | "jsx" | "ts" | "tsx" | "mjs" | "cjs" | "c" | "h" | "cc" | "cpp" | "cxx"
        | "hpp" | "hh" | "java" | "kt" | "kts" | "go" | "swift" | "scala" | "cs" | "php"
        | "dart" => Line("//"),
        // Hash line comments (shells, scripting, config).
        "py" | "rb" | "sh" | "bash" | "zsh" | "fish" | "pl" | "pm" | "r" | "yaml" | "yml"
        | "toml" | "cfg" | "conf" | "ps1" | "tf" | "nim" | "ex" | "exs" => Line("#"),
        // SQL / Lua / Haskell-style.
        "sql" | "lua" | "hs" | "elm" | "adb" | "ads" => Line("--"),
        // Lisp family.
        "lisp" | "clj" | "cljs" | "cljc" | "el" | "scm" => Line(";;"),
        // CSS block comments.
        "css" | "scss" | "less" => Block {
            open: "/*",
            close: "*/",
        },
        // Markup block comments (HTML/XML/Markdown share the HTML comment form).
        "html" | "htm" | "xhtml" | "xml" | "svg" | "vue" | "svelte" | "md" | "markdown" => Block {
            open: "<!--",
            close: "-->",
        },
        _ => return None,
    };
    Some(style)
}

/// Render the single-line banner for `source` in the given comment style (no
/// trailing newline).
pub fn render_banner(style: &CommentStyle, source: &Path) -> String {
    let text = format!(
        "{BANNER_MARKER} — do not edit this file; it is overwritten on every sync. \
         Edit the source instead: {}",
        source.display()
    );
    match style {
        CommentStyle::Line(prefix) => format!("{prefix} {text}"),
        CommentStyle::Block { open, close } => format!("{open} {text} {close}"),
    }
}

/// Produce the destination file's contents: `source`'s text with a fresh banner
/// on top. Any banner bukagu previously wrote is stripped first (idempotent), and
/// a leading BOM / shebang line is preserved above the banner.
pub fn with_banner(style: &CommentStyle, source: &Path, content: &str) -> String {
    let (prefix, after) = split_leading(content);
    let body = strip_existing(after);
    let banner = render_banner(style, source);
    // Match the file's existing newline style so a CRLF file stays all-CRLF.
    let nl = if content.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    if body.is_empty() {
        format!("{prefix}{banner}{nl}")
    } else {
        format!("{prefix}{banner}{nl}{nl}{body}")
    }
}

/// Split off a leading UTF-8 BOM and/or `#!` shebang line; the banner is inserted
/// after them. Returns `(prefix_to_keep_first, rest)`.
fn split_leading(content: &str) -> (&str, &str) {
    let mut idx = 0;
    if content.starts_with('\u{feff}') {
        idx += '\u{feff}'.len_utf8();
    }
    if content[idx..].starts_with("#!") {
        let after = &content[idx..];
        idx += after.find('\n').map_or(after.len(), |n| n + 1);
    }
    content.split_at(idx)
}

/// Drop a banner bukagu wrote on a previous sync: a leading line containing
/// [`BANNER_MARKER`] plus one immediately-following blank line. Returns `body`
/// unchanged when there's no such banner.
fn strip_existing(body: &str) -> &str {
    let line_end = body.find('\n').map_or(body.len(), |n| n + 1);
    let first_line = &body[..line_end];
    if !first_line
        .to_lowercase()
        .contains(&BANNER_MARKER.to_lowercase())
    {
        return body;
    }
    let mut rest = &body[line_end..];
    // Swallow exactly one blank separator line, if present.
    match rest.find('\n') {
        Some(nl) if rest[..nl].trim().is_empty() => rest = &rest[nl + 1..],
        None if rest.trim().is_empty() => rest = "",
        _ => {}
    }
    rest
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn src() -> PathBuf {
        PathBuf::from("/master/app.py")
    }

    #[test]
    fn comment_style_by_extension() {
        assert_eq!(comment_style("py"), Some(CommentStyle::Line("#")));
        assert_eq!(comment_style("ts"), Some(CommentStyle::Line("//")));
        assert_eq!(
            comment_style("JS"),
            Some(CommentStyle::Line("//")),
            "case-insensitive"
        );
        assert_eq!(comment_style("sql"), Some(CommentStyle::Line("--")));
        assert_eq!(
            comment_style("css"),
            Some(CommentStyle::Block {
                open: "/*",
                close: "*/"
            })
        );
        assert_eq!(
            comment_style("html"),
            Some(CommentStyle::Block {
                open: "<!--",
                close: "-->"
            })
        );
        assert_eq!(comment_style("bin"), None, "unknown extension");
        assert_eq!(comment_style(""), None, "no extension");
    }

    #[test]
    fn banner_carries_marker_and_source() {
        let b = render_banner(&CommentStyle::Line("#"), &src());
        assert!(b.starts_with("# "));
        assert!(b.contains(BANNER_MARKER));
        assert!(b.contains("/master/app.py"));
    }

    #[test]
    fn block_comment_wraps_the_banner() {
        let b = render_banner(
            &CommentStyle::Block {
                open: "<!--",
                close: "-->",
            },
            &src(),
        );
        assert!(b.starts_with("<!-- "));
        assert!(b.ends_with(" -->"));
    }

    #[test]
    fn with_banner_prepends_then_blank_line() {
        let out = with_banner(&CommentStyle::Line("#"), &src(), "print('hi')\n");
        let mut lines = out.lines();
        assert!(lines.next().unwrap().contains(BANNER_MARKER));
        assert_eq!(
            lines.next().unwrap(),
            "",
            "blank separator after the banner"
        );
        assert_eq!(lines.next().unwrap(), "print('hi')");
    }

    #[test]
    fn re_applying_does_not_stack_banners() {
        let style = CommentStyle::Line("//");
        let once = with_banner(&style, &src(), "const x = 1;\n");
        let twice = with_banner(&style, &src(), &once);
        assert_eq!(once, twice, "stripping makes a second pass a no-op");
        assert_eq!(twice.matches(BANNER_MARKER).count(), 1);
    }

    #[test]
    fn shebang_stays_on_the_first_line() {
        let out = with_banner(
            &CommentStyle::Line("#"),
            &src(),
            "#!/usr/bin/env python\nprint('hi')\n",
        );
        let mut lines = out.lines();
        assert_eq!(
            lines.next().unwrap(),
            "#!/usr/bin/env python",
            "shebang first"
        );
        assert!(
            lines.next().unwrap().contains(BANNER_MARKER),
            "banner after it"
        );
    }

    #[test]
    fn bom_is_preserved_before_the_banner() {
        let out = with_banner(&CommentStyle::Line("//"), &src(), "\u{feff}let x = 1;\n");
        assert!(out.starts_with('\u{feff}'), "BOM kept first");
        assert!(out[3..].starts_with("//"), "banner right after the BOM");
    }

    #[test]
    fn crlf_files_stay_crlf_and_dont_stack() {
        let style = CommentStyle::Line("//");
        let once = with_banner(&style, &src(), "const x = 1;\r\nconst y = 2;\r\n");
        assert!(once.contains("\r\n"), "CRLF newlines preserved");
        assert!(!once.contains("\n\n"), "no stray LF-only separators");
        // Re-applying over a CRLF banner is still idempotent.
        let twice = with_banner(&style, &src(), &once);
        assert_eq!(once, twice);
        assert_eq!(twice.matches(BANNER_MARKER).count(), 1);
    }
}
